### ISSUE TITLE
bug: Motor RPM parameter does not export to csv on dyno.

### ISSUE THREAD

**Issue by sco77m4r7in** [derekstavis/kilowatt#1]
**Describe the bug**

**To Reproduce**
2. Tap on '....'

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Kilowatt Version [e.g. build 25 patch 38427389]

**Additional context**

**Comment by derekstavis** [comment]
This has been solved in the latest release! Thanks for filing!
